# Site settings
title: Jonathon Arnold
email: jonathonarnold@me.com
description: Jon Arnold is a UX strategist, product manager, and workshop facilitator who cares.
url: "http://jonathonarnold.com" # the base hostname & protocol for your site
twitter_username: jonarnold
github_username:  jon-arnold

# Build settings
markdown: kramdown
paginate: 5
permalink: pretty
highlighter: rouge
